#pragma once

#include "Core/Log.h"
#include "Core/Application.h"
#include "Core/Layer.h"
#include "Core/Input.h"
#include "Core/KeyCodes.h"
#include "Core/Time.h"

#include "Renderer/Shader.h"
#include "Renderer/RenderCommand.h"
#include "Renderer/Renderer.h"
#include "Renderer/Renderer2D.h"
#include "Renderer/VertexArray.h"
#include "Renderer/Buffer.h"
#include "Renderer/Framebuffer.h"
#include "Renderer/Texture.h"
#include "Renderer/TextureManager.h"
#include "Renderer/SubTexture.h"
#include "Renderer/Camera.h"
#include "Renderer/Mesh.h"
#include "Renderer/MeshManager.h"

#include "Scene/Entity.h"
#include "Scene/Scene.h"
#include "Scene/Components/CameraComponent.h"
#include "Scene/Components/SpriteRenderComponent.h"
#include "Scene/Components/TransformComponent.h"
#include "Scene/Components/CameraComponent.h"
#include "Scene/Components/TagComponent.h"
#include "Scene/Components/MeshComponent.h"

#include "Events/ApplicationEvent.h"
#include "Events/MouseEvent.h"
#include "Events/KeyEvent.h"

#include "Utils/PlatformUtils.h"
#include "Utils/Math.h"

#include "glm/gtx/transform.hpp"
