#pragma once


namespace Volt
{
    namespace KeyCodes
    {
        enum EKeys
        {
            Unknown = -1,

            Space = 32,
            Apostrophe = 39,
            Comma = 44,
            Minus = 45,
            Period = 46,
            Slash = 47,

            Key0 = 48,
            Key1,
            Key2,
            Key3,
            Key4,
            Key5,
            Key6,
            Key7,
            Key8,
            Key9,

            Semicolon = 59,
            Equal = 61,

            A = 65,
            B,
            C,
            D,
            E,
            F,
            G,
            H,
            I,
            J,
            K,
            L,
            M,
            N,
            O,
            P,
            Q,
            R,
            S,
            T,
            U,
            V,
            W,
            X,
            Y,
            Z,

            LeftBracket = 91,
            Backslash,
            RightBracket,
            GraveAccent = 96,

            Escape = 256,
            Enter,
            Tab,
            Backspace,
            Insert,
            Delete,
            Right,
            Left,
            Down,
            Up,
            PageUp,
            PageDown,
            Home,
            End,
            CapsLock = 280,
            ScrollLock,
            NumLock,
            PrintScreen,
            Pause,
            F1 = 290,
            F2,
            F3,
            F4,
            F5,
            F6,
            F7,
            F8,
            F9,
            F10,
            F11,
            F12,
            F13,
            F14,
            F15,
            F16,
            F17,
            F18,
            F19,
            F20,
            F21,
            F22,
            F23,
            F24,
            F25,

            KP0 = 320,
            KP1,
            KP2,
            KP3,
            KP4,
            KP5,
            KP6,
            KP7,
            KP8,
            KP9,
            KP_Decimal,
            KP_Divide,
            KP_Multiply,
            KP_Subtract,
            KP_Add,
            KP_Enter,
            KP_Equal,

            LeftShift = 340,
            LeftControl,
            LeftAlt,
            LeftSuper,
            RightShift,
            RightControl,
            RightAlt,
            RightSuper,
            Menu
        };
    }
}
